# Generated by Django 4.1.1 on 2022-10-05 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("httpservice", "0001_initial"),
        ("httpservice", "0002_alter_city_options_alter_shop_options_and_more"),
        ("httpservice", "0003_alter_shop_city_alter_shop_street"),
        ("httpservice", "0004_remove_shop_city_remove_shop_street"),
        ("httpservice", "0005_shop_city"),
        ("httpservice", "0006_shop_street_alter_shop_city"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="httpservice.city",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=5)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="httpservice.city",
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="httpservice.street",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
