# Generated by Django 4.1.1 on 2022-10-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("httpservice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="street",
            options={"ordering": ["-id"]},
        ),
    ]
