# Generated by Django 4.1.1 on 2022-10-03 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("httpservice", "0002_alter_city_options_alter_shop_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="httpservice.city",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="street",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="httpservice.street",
            ),
        ),
    ]
