# Generated by Django 4.1.1 on 2022-10-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("httpservice", "0003_alter_shop_city_alter_shop_street"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="city",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="street",
        ),
    ]
