# Generated by Django 4.1.1 on 2022-10-03 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("httpservice", "0004_remove_shop_city_remove_shop_street"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="httpservice.city",
            ),
        ),
    ]
