# Generated by Django 4.1.1 on 2022-10-03 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("httpservice", "0005_shop_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="street",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="httpservice.street",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="httpservice.city"
            ),
        ),
    ]
